import { Repository, Contributor, GitHubEvent, Milestone, Badge, DashboardStats } from '../types';

export const mockRepositories: Repository[] = [
  {
    id: '1',
    github_id: 123456789,
    name: 'awesome-project',
    full_name: 'opensource/awesome-project',
    owner: 'opensource',
    description: 'An amazing open source project that helps developers',
    stars_count: 1250,
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    github_id: 987654321,
    name: 'react-toolkit',
    full_name: 'devtools/react-toolkit',
    owner: 'devtools',
    description: 'Essential React development toolkit',
    stars_count: 850,
    created_at: new Date('2024-03-20').toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockContributors: Contributor[] = [
  {
    id: 'c1',
    github_id: 111111,
    username: 'sarah-dev',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    profile_url: 'https://github.com/sarah-dev',
    created_at: new Date('2024-01-20').toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c2',
    github_id: 222222,
    username: 'mike-coder',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mike',
    profile_url: 'https://github.com/mike-coder',
    created_at: new Date('2024-02-10').toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c3',
    github_id: 333333,
    username: 'alex-opensource',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    profile_url: 'https://github.com/alex-opensource',
    created_at: new Date('2024-01-25').toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c4',
    github_id: 444444,
    username: 'jamie-tech',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jamie',
    profile_url: 'https://github.com/jamie-tech',
    created_at: new Date('2024-03-01').toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: 'm1',
    repository_id: '1',
    contributor_id: 'c1',
    milestone_type: 'pr_count',
    milestone_value: 50,
    title: '50 Pull Requests Merged',
    description: 'sarah-dev has successfully merged 50 pull requests in awesome-project',
    achieved_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    notified_slack: true,
    notified_discord: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    repository: mockRepositories[0],
    contributor: mockContributors[0],
  },
  {
    id: 'm2',
    repository_id: '1',
    milestone_type: 'stars_reached',
    milestone_value: 1000,
    title: '1,000 Stars Reached',
    description: 'awesome-project has reached 1,000 stars on GitHub',
    achieved_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    notified_slack: true,
    notified_discord: true,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    repository: mockRepositories[0],
  },
  {
    id: 'm3',
    contributor_id: 'c2',
    milestone_type: 'commit_count',
    milestone_value: 100,
    title: '100 Commits Celebration',
    description: 'mike-coder has made 100 commits across all tracked repositories',
    achieved_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    notified_slack: false,
    notified_discord: false,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    contributor: mockContributors[1],
  },
  {
    id: 'm4',
    repository_id: '2',
    contributor_id: 'c3',
    milestone_type: 'issue_count',
    milestone_value: 25,
    title: '25 Issues Opened',
    description: 'alex-opensource has opened 25 helpful issues in react-toolkit',
    achieved_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    notified_slack: true,
    notified_discord: true,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    repository: mockRepositories[1],
    contributor: mockContributors[2],
  },
  {
    id: 'm5',
    contributor_id: 'c1',
    milestone_type: 'contribution_anniversary',
    milestone_value: 1,
    title: '1 Year of Contributions',
    description: 'sarah-dev is celebrating 1 year of contributions to the community',
    achieved_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    notified_slack: true,
    notified_discord: true,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    contributor: mockContributors[0],
  },
];

export const mockEvents: GitHubEvent[] = [
  {
    id: 'e1',
    repository_id: '1',
    contributor_id: 'c1',
    event_type: 'pr_merged',
    event_data: { pr_number: 142, title: 'Add new feature' },
    github_event_id: 'gh_e1',
    occurred_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'e2',
    repository_id: '1',
    event_type: 'star',
    event_data: { starred_by: 'new-user' },
    github_event_id: 'gh_e2',
    occurred_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'e3',
    repository_id: '2',
    contributor_id: 'c3',
    event_type: 'issue_opened',
    event_data: { issue_number: 89, title: 'Bug in component' },
    github_event_id: 'gh_e3',
    occurred_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalEvents: 156,
  totalMilestones: 12,
  totalContributors: 4,
  totalRepositories: 2,
  recentMilestones: mockMilestones.slice(0, 5),
  topContributors: [
    { ...mockContributors[0], milestone_count: 5 },
    { ...mockContributors[1], milestone_count: 3 },
    { ...mockContributors[2], milestone_count: 2 },
    { ...mockContributors[3], milestone_count: 1 },
  ],
};
